stages:
  - test

test_latest:
  stage: test
  image: registry.gitlab.dkrz.de/freva/evaluation_system/freva_build:freva-dev
  variables:
    CONDA: "Miniconda3-latest"
  tags:
    - docker, specific
  before_script:
    - conda env create -f conda-env.yml
  script:
    - conda run -n $CONDA_ENV make lint
    # Do the unit tests
    # - /tmp/freva_web/bin/python -m pytest -v tests
  artifacts:
    when: always
