stages:
  - build
  - test


build-image:
    stage: build
    needs: []
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - if [ -n "$CI_COMMIT_BRANCH" ]; then IMAGETAG="$CI_COMMIT_BRANCH"; else IMAGETAG="$CI_COMMIT_SHA"; fi
        - echo $CI_COMMIT_BRANCH
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR
                       --cleanup
                       --skip-unused-stages=true
                       --ignore-var-run
                       --dockerfile $CI_PROJECT_DIR/Dockerfile
                       --destination $CI_REGISTRY_IMAGE/freva_web:$CI_COMMIT_BRANCH
    tags:
        - docker, specific
    rules:
        - if: "$CI_COMMIT_BRANCH == 'main'"
        - if: "$CI_COMMIT_BRANCH != 'main'"

test_latest:
  stage: test
  needs: []
  image: registry.gitlab.dkrz.de/freva/evaluation_system/freva-dev:unittest
  tags:
    - docker, specific
  before_script:
    - /usr/bin/python3 .ci/install_conda.py /tmp/anaconda3 conda-env.yml -s
  script:
    - /tmp/anaconda3/bin/conda run make lint
    - /tmp/anaconda3/bin/conda run make tests
  artifacts:
    when: always
