name: freva-web
channels:
  - conda-forge
dependencies:
  - black
  - bleach
  - conda
  - configparser
  - coverage
  - distributed
  - django-debug-toolbar
  - django-ipware
  - django-nose
  - django-webpack-loader
  - djangorestframework
  - fabric
  - git
  - gunicorn
  - markdown
  - mock
  - mod_wsgi
  - mypy
  - mysqlclient
  - nbval
  - nodejs
  - nose
  - pandoc
  - paramiko
  - pep8
  - pip
  - pip:
    - requests_mock
    - django-auth-ldap
    - django-datatable-view
    - django-templated-email
    - django_compressor
    - django-debug-toolbar-user-panel
    - django-discover-runner
    - django-bootstrap-v5
    - django-model-utils
    - freva
    - pep257
    - types-requests
    - types-toml
    - hurry.filesize
    - git+https://gitlab.dkrz.de/freva/evaluation_system.git
    - git+https://gitlab.dkrz.de/freva/metadata-inspektor.git
  - pygtail
  - pylint
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-html
  - python-ldap
  - redis-py
  - requests-mock
  - sphinx
  - testpath
