version: "3.9"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
    volumes:
      - ./docker/config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
    depends_on:
      - redis
      - solr
      - databrowser
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./docker/config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./docker/config/solr/create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: search_stats
    ports:
      - "27017:27017"
  databrowser:
    image: ghcr.io/freva-clint/databrowserapi:latest
    ports:
      - 7777:8080
    environment:
      MONGO_HOST: mongodb:27017
      MONGO_PASSWORD: secret
      MONGO_DB: search_stats
      MONGO_USER: mongo
      SOLR_HOST: solr:8983
    depends_on:
      - solr
    command: ["sh", "-c", "sleep 3 && /opt/app/python/bin/python3 -m databrowser.cli --debug --dev"]
