version: "3.9"
services:
  db:
    image: mariadb:11.3
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
    volumes:
      - ./docker/config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
    depends_on:
      - solr
  solr:
    networks:
      - freva-web
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./docker/config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./docker/config/solr/create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
      - ./docker/config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
    hostname: solr
  redis:
    networks:
      - freva-web
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWD}
      REDIS_LOGLEVEL: debug
      REDIS_SSL_CERTFILE: ${REDIS_CONTAINER_CERTFILE}
      REDIS_SSL_KEYFILE: ${REDIS_CONTAINER_KEYFILE}
    hostname: redis
    volumes:
      - ./docker/config/redis/redis-cmd.sh:/usr/local/bin/redis-cmd
      - ./docker/config/certs:/certs
    command: /usr/local/bin/redis-cmd
  keycloak:
    networks:
      - freva-web
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      JAVA_OPTS_APPEND: "-Djava.net.preferIPv4Stack=true"
    hostname: keycloak
    volumes:
      - ./docker/config/certs:/certs
      - ./docker/config/keycloak/import:/opt/keycloak/data/import:z
    ports:
      - "8080:8080"
      - "8443:8443"
    command: |
         start-dev
         --hostname-strict=false
         --import-realm
         -Dkeycloak.migration.strategy=OVERWRITE_EXISTING

  keycloak-bootstrap:
    image: docker.io/badouralix/curl-jq
    depends_on:
      - keycloak
    volumes:
      - ./docker/create-user.sh:/create-user.sh:ro
    environment:
      USER: ${USER}
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: secret
      KEYCLOAK_HOST: keycloak:8080
    entrypoint: ["sh", "/create-user.sh"]
    networks:
      - freva-web
  mongodb:
    image: mongo:latest
    networks:
      - freva-web
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: search_stats
    ports:
      - "27017:27017"
    hostname: mongodb
networks:
  freva-web:
    driver: bridge
