version: "3.9"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
    volumes:
      - ./docker/config/mysql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
  solr:
    image: solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./docker/config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./docker/config/solr/create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
