name: Tests
run-name: ${{ github.actor }} is doing some smoke tests

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up services
        run: docker-compose up -d --remove-orphans
      - name: Create conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freva-web
          environment-file: conda-env.yml
          python-version: "3.11"
          auto-activate-base: false
      - name: Run checks in python
        run: make tests
      - name: Lint python
        run: make lint
      - name: Prepare node
        run: npm install
      - name: Lint js formatting
        run: npm run lint-format
      - name: Lint javascript
        run: npm run lint
