name: Tests
run-name: ${{ github.actor }} is doing some smoke tests

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up services
        run: docker-compose up -d --remove-orphans
      - name: Create conda env
        # https://github.com/marketplace/actions/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: freva-web
          environment-file: conda-env.yml
          cache-environment: false
          cache-downloads: false
          init-shell: bash
      - name: Lint js code and python
        run: micromamba run -n freva-web make lint
      - name: Run build checks for js and python smoke tests
        run: micromamba run -n freva-web make tests
