name: Tests
run-name: ${{ github.actor }} is doing some smoke tests

on: [push, pull_request, workflow_call]
jobs:
  Smoke-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create conda env
        # https://github.com/marketplace/actions/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: freva-web
          environment-file: dev-env.yml
          cache-environment: false
          cache-downloads: false
          init-shell: bash
      - name: Generate self signed certs
        run: >
          micromamba run -n freva-web python docker/config/dev-utils.py gen-certs
      - name: Set up services
        run: docker compose up -d --remove-orphans
      - name: Lint js code and python
        run: micromamba run -n freva-web make lint
      - name: Run build checks for js and python smoke tests
        run: micromamba run -n freva-web make tests

  multi-platform-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build node code
        run: |
          npm install
          npm run build-production

      - name: Build freva-web image for ${{ matrix.platform }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERSION=test
            BUNDLE_HOST_PATH=${{ github.workspace }}
          platforms: ${{ matrix.platform }}
          push: false
          no-cache: true
          tags: freva-web:latest
